language: cpp
before_script:
  - sudo apt-get install libgtest-dev cmake -y
  - cd /usr/src/gtest && cmake CMakeLists.txt && make
  - cp /usr/src/gtest/*.a /usr/lib
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
   - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -udeepdivenow:$BINTRAY_API_KEY "https://api.bintray.com/content/deepdivenow/otus/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
